print(" Hello, World!")
print("Day 1 starts now.")
print("This is the frist day of the 100 Days of code challenge")
print("I am excided to start this challenge and learn new things")
print("I am going to code every day for the next 100 days and share my progress with you all")
print("I am going to learn Python,and I am going to build some cool projects along the way")
print("I am going to have fun and learn a lot in the process")
print("I am going to be consistent and dedicated to this challenge and I am going to achieve my goals")
print("I am going to be pround of myseft for completing this challenge and I am going to be greatful for the opportunity to learn and grow as a programmer")
print("I am going to be a better programmer and I am going to be a better person because of this challenge")
print("I am going to be a part of a community of like-minded individuals who are also on this journey and I am going to supporta and encourage each other along the way")
print("I am going to be a part of a community of like-minded inviduals who are also on this journey and I am going to supporta and encourage each other along the wat")
print("I am going to be a part of a community of like-minded inviduals who are also on this journey and I am gooing to supporta and encourage each other along the way")
print("I am going to be a part of a community of like-minded inviduals who are also on this journey and I am going to supporta and encourage each other along the way")
print("I am going to be a part of a community of like-minded inviduals who are also on this journey and I am going to supporta and encourage each other along the way")